development:
  adapter: postgresql
  encoding: unicode
  database: phillips_jewelers_development
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: phillips_jewelers_test
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: phillips_jewelers_production
  username: production
  password:
  host: localhost